version: 1.0.{build}
image: Visual Studio 2022
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget.exe restore VSProjNuGetVersionUpdater.sln
build:
  project: VSProjNuGetVersionUpdater.sln
  verbosity: minimal
artifacts:
- path: bin\Release
  name: VSProjNuGetVersionUpdater
